# Meta
title: 狸猫校

author: Liebe Grüße,
email: anthony.pi@education.nsw.gov.au

description: 
  Built with two cups of coffee and lots of love. ☕️❤️

baseurl: "/" 
url: "https://wildflowering.github.io/" # base hostname & protocol
github_username:  wildflowering


# Build settings
theme: minima
plugins:
  - jekyll-feed

markdown: kramdown

show_excerpts: true


# Site content
header_pages:
  - _pages/lessons.md
  - _pages/about.md

collections:
  lessons:
    output: true


# Include/exclude
include:
  - _pages

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
